
main:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./main ./main.c -lrt -lpthread

thread:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./thread ./thread.c -lrt -lpthread

pipe:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./pipe ./pipe.c -lrt -lpthread

pipe_dup2:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./pipe_dup2 ./pipe_dup2.c -lrt -lpthread

kill_signal:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./kill_signal ./kill_signal.c -lrt -lpthread

share_memory:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./share_memory ./share_memory.c -lrt -lpthread

atomic:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./atomic ./atomic.c -lrt -lpthread

spin_lock:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./spin_lock ./spin_lock.c -lrt -lpthread

semaphore:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./semaphore ./semaphore.c -lrt -lpthread

mutex:
	gcc -O0 -std=gnu11 -Werror -Wall -Wno-unused-result -o ./mutex ./mutex.c -lrt -lpthread

clean:
	rm -f main
	rm -f thread
	rm -f pipe
	rm -f pipe_dup2
	rm -f kill_signal
	rm -f share_memory
	rm -f atomic
	rm -f spin_lock
	rm -f semaphore
	rm -f mutex
